sudo: true
# dist: trusty

language: python

python:
  - 2.7

# services:
# 
# matrix:
#   include:
#     - os: linux
#      compiler: gcc

before_install:
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - export GIT_VER=`git describe --tags`
  - export VERSION=`python -c "print '$GIT_VER'.split('-')[0][1:]"`
  - export MCVINE_CONDA_PKG_VER=${VERSION}unstable
  - echo ${TRAVIS_PYTHON_VERSION}
  - conda config --set always_yes true
  - conda update conda
  - conda config --add channels conda-forge
  - conda config --add channels diffpy
  - conda config --add channels mcvine
  - conda install -n root conda-build
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - conda install -n testenv anaconda-client
  - source activate testenv
  - conda config --set anaconda_upload no
  - cd builders/travis-conda
  - ./create_meta_yaml $MCVINE_CONDA_PKG_VER $GIT_FULL_HASH
  - grep version meta.yaml
  - grep git_rev meta.yaml
  - CORES=2 conda build .
  - anaconda -t $CONDA_UPLOAD_TOKEN upload --force /home/travis/mc/conda-bld/linux-64/mcvine-core-$MCVINE_CONDA_PKG_VER-*.tar.bz2 --label unstable
  - cd ../..
  - conda install mcvine --use-local

script:
  - python -c TestSample.py
  - echo "mcvine"


